# Generated by Django 3.1 on 2022-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210907_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_slider',
            field=models.ImageField(blank=True, upload_to='photos/categories', verbose_name='384 x 660'),
        ),
    ]
