# Generated by Django 3.2.4 on 2022-08-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20220811_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_details',
        ),
    ]
